/// <summary>
/// Simple test template that generates a basic class
/// </summary>
void Main()
{
    WriteLine("using System;");
    WriteLine("");
    WriteLine("namespace TestNamespace");
    WriteLine("{");
    WriteLine("    public class GeneratedTestClass");
    WriteLine("    {");
    WriteLine("        public string Message => \"Generated by CodegenCS\";");
    WriteLine("    }");
    WriteLine("}");
}
