// Simple CodegenCS Template for testing
using System;

public class HelloTemplate
{
    FormattableString Main()
    {
        return $@"""
// This file was auto-generated by CodegenCS Source Generator
namespace Generated
{{
    public class HelloWorld
    {{
        public static string GetMessage() => ""Hello from CodegenCS!"";
    }}
}}
""";
    }
}
